import { createFileRoute } from "@tanstack/react-router";

import { LegalPage } from "@/components/layout/LegalPage";
import { siteConfig } from "@/config/site";

export const Route = createFileRoute("/disclaimer")({
  head: () => ({
    meta: [
      { title: `Disclaimer — ${siteConfig.name}` },
      {
        name: "description",
        content: `${siteConfig.name} provides independent PTE practice material. Scores are practice estimates and are not official PTE results.`,
      },
      { property: "og:title", content: `Disclaimer — ${siteConfig.name}` },
      { property: "og:description", content: "Practice scores are estimates, not official results." },
    ],
  }),
  component: DisclaimerPage,
});

function DisclaimerPage() {
  return (
    <LegalPage title="Disclaimer" updated="4 August 2026">
      <section>
        <h2>Independent practice material</h2>
        <p>
          {siteConfig.name} is an independent practice platform operated by{" "}
          {siteConfig.company.legalName}. We are not affiliated with, endorsed by or sponsored by
          Pearson or any official PTE test provider. "PTE" and related marks belong to their
          respective owners and are used only to describe the exam our material prepares you for.
        </p>
      </section>
      <section>
        <h2>Scores are estimates</h2>
        <p>
          Scores and feedback are generated by automated and AI-assisted systems for practice
          purposes. They indicate likely performance ranges and may differ from official results. No
          guarantee is made about the score you will achieve in a real exam.
        </p>
      </section>
      <section>
        <h2>AI feedback limitations</h2>
        <ul>
          <li>AI feedback may occasionally be incomplete or incorrect.</li>
          <li>Feedback should be used alongside guidance from a qualified teacher where possible.</li>
          <li>Audio quality and microphone hardware affect Speaking scores.</li>
        </ul>
      </section>
      <section>
        <h2>No professional advice</h2>
        <p>
          Content on this site is educational and does not constitute migration, legal or admissions
          advice. Check requirements with the relevant institution or authority.
        </p>
      </section>
    </LegalPage>
  );
}
