-- 0006_test_template_seed.sql — default module + mock test templates
-- GENERATED by scripts/gen-template-seed.ts — do not edit by hand.
-- Apply with: wrangler d1 migrations apply pte_portal

PRAGMA foreign_keys = ON;

INSERT OR REPLACE INTO test_templates (id, slug, name, description, test_type, module_key, difficulty,
  price, currency, question_count, time_limit_minutes, target_score, instructions, is_active, purchasable,
  version, created_by, created_at, updated_at) VALUES (
  'tpl_speaking_easy', 'speaking-easy', 'Speaking — Easy', 'Thirty spoken tasks covering read aloud, repeat sentence, describe image, retell lecture and short answers.', 'module', 'speaking',
  'easy', 1, 'AUD', 30,
  30, 50, 'Complete every task in order. Timing is per task where the PTE exam is timed per task; the overall limit applies to the whole test.', 0, 1, 1, NULL, '2026-01-05T00:00:00.000Z', '2026-01-05T00:00:00.000Z');
DELETE FROM test_template_rules WHERE template_id = 'tpl_speaking_easy';
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_speaking-easy_read_aloud', 'tpl_speaking_easy', 'read_aloud', 6, NULL, 1, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_speaking-easy_repeat_sentence', 'tpl_speaking_easy', 'repeat_sentence', 8, NULL, 2, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_speaking-easy_describe_image', 'tpl_speaking_easy', 'describe_image', 5, NULL, 3, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_speaking-easy_retell_lecture', 'tpl_speaking_easy', 'retell_lecture', 3, NULL, 4, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_speaking-easy_answer_short_question', 'tpl_speaking_easy', 'answer_short_question', 5, NULL, 5, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_speaking-easy_respond_to_situation', 'tpl_speaking_easy', 'respond_to_situation', 2, NULL, 6, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_speaking-easy_summarize_group_discussion', 'tpl_speaking_easy', 'summarize_group_discussion', 1, NULL, 7, '2026-01-05T00:00:00.000Z');

INSERT OR REPLACE INTO test_templates (id, slug, name, description, test_type, module_key, difficulty,
  price, currency, question_count, time_limit_minutes, target_score, instructions, is_active, purchasable,
  version, created_by, created_at, updated_at) VALUES (
  'tpl_speaking_intermediate', 'speaking-intermediate', 'Speaking — Intermediate', 'Thirty spoken tasks covering read aloud, repeat sentence, describe image, retell lecture and short answers.', 'module', 'speaking',
  'intermediate', 1, 'AUD', 30,
  30, 65, 'Complete every task in order. Timing is per task where the PTE exam is timed per task; the overall limit applies to the whole test.', 0, 1, 1, NULL, '2026-01-05T00:00:00.000Z', '2026-01-05T00:00:00.000Z');
DELETE FROM test_template_rules WHERE template_id = 'tpl_speaking_intermediate';
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_speaking-intermediate_read_aloud', 'tpl_speaking_intermediate', 'read_aloud', 6, NULL, 1, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_speaking-intermediate_repeat_sentence', 'tpl_speaking_intermediate', 'repeat_sentence', 8, NULL, 2, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_speaking-intermediate_describe_image', 'tpl_speaking_intermediate', 'describe_image', 5, NULL, 3, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_speaking-intermediate_retell_lecture', 'tpl_speaking_intermediate', 'retell_lecture', 3, NULL, 4, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_speaking-intermediate_answer_short_question', 'tpl_speaking_intermediate', 'answer_short_question', 5, NULL, 5, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_speaking-intermediate_respond_to_situation', 'tpl_speaking_intermediate', 'respond_to_situation', 2, NULL, 6, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_speaking-intermediate_summarize_group_discussion', 'tpl_speaking_intermediate', 'summarize_group_discussion', 1, NULL, 7, '2026-01-05T00:00:00.000Z');

INSERT OR REPLACE INTO test_templates (id, slug, name, description, test_type, module_key, difficulty,
  price, currency, question_count, time_limit_minutes, target_score, instructions, is_active, purchasable,
  version, created_by, created_at, updated_at) VALUES (
  'tpl_speaking_hard', 'speaking-hard', 'Speaking — Hard', 'Thirty spoken tasks covering read aloud, repeat sentence, describe image, retell lecture and short answers.', 'module', 'speaking',
  'hard', 1, 'AUD', 30,
  30, 79, 'Complete every task in order. Timing is per task where the PTE exam is timed per task; the overall limit applies to the whole test.', 0, 1, 1, NULL, '2026-01-05T00:00:00.000Z', '2026-01-05T00:00:00.000Z');
DELETE FROM test_template_rules WHERE template_id = 'tpl_speaking_hard';
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_speaking-hard_read_aloud', 'tpl_speaking_hard', 'read_aloud', 6, NULL, 1, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_speaking-hard_repeat_sentence', 'tpl_speaking_hard', 'repeat_sentence', 8, NULL, 2, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_speaking-hard_describe_image', 'tpl_speaking_hard', 'describe_image', 5, NULL, 3, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_speaking-hard_retell_lecture', 'tpl_speaking_hard', 'retell_lecture', 3, NULL, 4, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_speaking-hard_answer_short_question', 'tpl_speaking_hard', 'answer_short_question', 5, NULL, 5, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_speaking-hard_respond_to_situation', 'tpl_speaking_hard', 'respond_to_situation', 2, NULL, 6, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_speaking-hard_summarize_group_discussion', 'tpl_speaking_hard', 'summarize_group_discussion', 1, NULL, 7, '2026-01-05T00:00:00.000Z');

INSERT OR REPLACE INTO test_templates (id, slug, name, description, test_type, module_key, difficulty,
  price, currency, question_count, time_limit_minutes, target_score, instructions, is_active, purchasable,
  version, created_by, created_at, updated_at) VALUES (
  'tpl_reading_easy', 'reading-easy', 'Reading — Easy', 'Thirty reading tasks covering fill in the blanks, re-order paragraphs and multiple choice questions.', 'module', 'reading',
  'easy', 1, 'AUD', 30,
  32, 50, 'Complete every task in order. Timing is per task where the PTE exam is timed per task; the overall limit applies to the whole test.', 0, 1, 1, NULL, '2026-01-05T00:00:00.000Z', '2026-01-05T00:00:00.000Z');
DELETE FROM test_template_rules WHERE template_id = 'tpl_reading_easy';
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_reading-easy_reading_writing_fill_blanks', 'tpl_reading_easy', 'reading_writing_fill_blanks', 8, NULL, 1, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_reading-easy_reading_mcq_multiple', 'tpl_reading_easy', 'reading_mcq_multiple', 5, NULL, 2, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_reading-easy_reorder_paragraphs', 'tpl_reading_easy', 'reorder_paragraphs', 6, NULL, 3, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_reading-easy_reading_fill_blanks', 'tpl_reading_easy', 'reading_fill_blanks', 7, NULL, 4, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_reading-easy_reading_mcq_single', 'tpl_reading_easy', 'reading_mcq_single', 4, NULL, 5, '2026-01-05T00:00:00.000Z');

INSERT OR REPLACE INTO test_templates (id, slug, name, description, test_type, module_key, difficulty,
  price, currency, question_count, time_limit_minutes, target_score, instructions, is_active, purchasable,
  version, created_by, created_at, updated_at) VALUES (
  'tpl_reading_intermediate', 'reading-intermediate', 'Reading — Intermediate', 'Thirty reading tasks covering fill in the blanks, re-order paragraphs and multiple choice questions.', 'module', 'reading',
  'intermediate', 1, 'AUD', 30,
  32, 65, 'Complete every task in order. Timing is per task where the PTE exam is timed per task; the overall limit applies to the whole test.', 0, 1, 1, NULL, '2026-01-05T00:00:00.000Z', '2026-01-05T00:00:00.000Z');
DELETE FROM test_template_rules WHERE template_id = 'tpl_reading_intermediate';
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_reading-intermediate_reading_writing_fill_blanks', 'tpl_reading_intermediate', 'reading_writing_fill_blanks', 8, NULL, 1, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_reading-intermediate_reading_mcq_multiple', 'tpl_reading_intermediate', 'reading_mcq_multiple', 5, NULL, 2, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_reading-intermediate_reorder_paragraphs', 'tpl_reading_intermediate', 'reorder_paragraphs', 6, NULL, 3, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_reading-intermediate_reading_fill_blanks', 'tpl_reading_intermediate', 'reading_fill_blanks', 7, NULL, 4, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_reading-intermediate_reading_mcq_single', 'tpl_reading_intermediate', 'reading_mcq_single', 4, NULL, 5, '2026-01-05T00:00:00.000Z');

INSERT OR REPLACE INTO test_templates (id, slug, name, description, test_type, module_key, difficulty,
  price, currency, question_count, time_limit_minutes, target_score, instructions, is_active, purchasable,
  version, created_by, created_at, updated_at) VALUES (
  'tpl_reading_hard', 'reading-hard', 'Reading — Hard', 'Thirty reading tasks covering fill in the blanks, re-order paragraphs and multiple choice questions.', 'module', 'reading',
  'hard', 1, 'AUD', 30,
  32, 79, 'Complete every task in order. Timing is per task where the PTE exam is timed per task; the overall limit applies to the whole test.', 0, 1, 1, NULL, '2026-01-05T00:00:00.000Z', '2026-01-05T00:00:00.000Z');
DELETE FROM test_template_rules WHERE template_id = 'tpl_reading_hard';
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_reading-hard_reading_writing_fill_blanks', 'tpl_reading_hard', 'reading_writing_fill_blanks', 8, NULL, 1, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_reading-hard_reading_mcq_multiple', 'tpl_reading_hard', 'reading_mcq_multiple', 5, NULL, 2, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_reading-hard_reorder_paragraphs', 'tpl_reading_hard', 'reorder_paragraphs', 6, NULL, 3, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_reading-hard_reading_fill_blanks', 'tpl_reading_hard', 'reading_fill_blanks', 7, NULL, 4, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_reading-hard_reading_mcq_single', 'tpl_reading_hard', 'reading_mcq_single', 4, NULL, 5, '2026-01-05T00:00:00.000Z');

INSERT OR REPLACE INTO test_templates (id, slug, name, description, test_type, module_key, difficulty,
  price, currency, question_count, time_limit_minutes, target_score, instructions, is_active, purchasable,
  version, created_by, created_at, updated_at) VALUES (
  'tpl_writing_easy', 'writing-easy', 'Writing — Easy', 'Three full writing tasks: two Summarize Written Text responses and one 200–300 word essay. Writing is deliberately configured with a practical task count rather than 30 responses.', 'module', 'writing',
  'easy', 1, 'AUD', 3,
  40, 50, 'Complete every task in order. Timing is per task where the PTE exam is timed per task; the overall limit applies to the whole test.', 0, 1, 1, NULL, '2026-01-05T00:00:00.000Z', '2026-01-05T00:00:00.000Z');
DELETE FROM test_template_rules WHERE template_id = 'tpl_writing_easy';
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_writing-easy_summarize_written_text', 'tpl_writing_easy', 'summarize_written_text', 2, NULL, 1, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_writing-easy_write_essay', 'tpl_writing_easy', 'write_essay', 1, NULL, 2, '2026-01-05T00:00:00.000Z');

INSERT OR REPLACE INTO test_templates (id, slug, name, description, test_type, module_key, difficulty,
  price, currency, question_count, time_limit_minutes, target_score, instructions, is_active, purchasable,
  version, created_by, created_at, updated_at) VALUES (
  'tpl_writing_intermediate', 'writing-intermediate', 'Writing — Intermediate', 'Three full writing tasks: two Summarize Written Text responses and one 200–300 word essay. Writing is deliberately configured with a practical task count rather than 30 responses.', 'module', 'writing',
  'intermediate', 1, 'AUD', 3,
  40, 65, 'Complete every task in order. Timing is per task where the PTE exam is timed per task; the overall limit applies to the whole test.', 0, 1, 1, NULL, '2026-01-05T00:00:00.000Z', '2026-01-05T00:00:00.000Z');
DELETE FROM test_template_rules WHERE template_id = 'tpl_writing_intermediate';
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_writing-intermediate_summarize_written_text', 'tpl_writing_intermediate', 'summarize_written_text', 2, NULL, 1, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_writing-intermediate_write_essay', 'tpl_writing_intermediate', 'write_essay', 1, NULL, 2, '2026-01-05T00:00:00.000Z');

INSERT OR REPLACE INTO test_templates (id, slug, name, description, test_type, module_key, difficulty,
  price, currency, question_count, time_limit_minutes, target_score, instructions, is_active, purchasable,
  version, created_by, created_at, updated_at) VALUES (
  'tpl_writing_hard', 'writing-hard', 'Writing — Hard', 'Three full writing tasks: two Summarize Written Text responses and one 200–300 word essay. Writing is deliberately configured with a practical task count rather than 30 responses.', 'module', 'writing',
  'hard', 1, 'AUD', 3,
  40, 79, 'Complete every task in order. Timing is per task where the PTE exam is timed per task; the overall limit applies to the whole test.', 0, 1, 1, NULL, '2026-01-05T00:00:00.000Z', '2026-01-05T00:00:00.000Z');
DELETE FROM test_template_rules WHERE template_id = 'tpl_writing_hard';
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_writing-hard_summarize_written_text', 'tpl_writing_hard', 'summarize_written_text', 2, NULL, 1, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_writing-hard_write_essay', 'tpl_writing_hard', 'write_essay', 1, NULL, 2, '2026-01-05T00:00:00.000Z');

INSERT OR REPLACE INTO test_templates (id, slug, name, description, test_type, module_key, difficulty,
  price, currency, question_count, time_limit_minutes, target_score, instructions, is_active, purchasable,
  version, created_by, created_at, updated_at) VALUES (
  'tpl_listening_easy', 'listening-easy', 'Listening — Easy', 'Thirty listening tasks covering summarise spoken text, dictation, fill in the blanks and highlight incorrect words.', 'module', 'listening',
  'easy', 1, 'AUD', 30,
  35, 50, 'Complete every task in order. Timing is per task where the PTE exam is timed per task; the overall limit applies to the whole test.', 0, 1, 1, NULL, '2026-01-05T00:00:00.000Z', '2026-01-05T00:00:00.000Z');
DELETE FROM test_template_rules WHERE template_id = 'tpl_listening_easy';
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_listening-easy_summarize_spoken_text', 'tpl_listening_easy', 'summarize_spoken_text', 2, NULL, 1, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_listening-easy_listening_mcq_multiple', 'tpl_listening_easy', 'listening_mcq_multiple', 4, NULL, 2, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_listening-easy_listening_fill_blanks', 'tpl_listening_easy', 'listening_fill_blanks', 4, NULL, 3, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_listening-easy_highlight_correct_summary', 'tpl_listening_easy', 'highlight_correct_summary', 4, NULL, 4, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_listening-easy_listening_mcq_single', 'tpl_listening_easy', 'listening_mcq_single', 4, NULL, 5, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_listening-easy_select_missing_word', 'tpl_listening_easy', 'select_missing_word', 4, NULL, 6, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_listening-easy_highlight_incorrect_words', 'tpl_listening_easy', 'highlight_incorrect_words', 4, NULL, 7, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_listening-easy_write_from_dictation', 'tpl_listening_easy', 'write_from_dictation', 4, NULL, 8, '2026-01-05T00:00:00.000Z');

INSERT OR REPLACE INTO test_templates (id, slug, name, description, test_type, module_key, difficulty,
  price, currency, question_count, time_limit_minutes, target_score, instructions, is_active, purchasable,
  version, created_by, created_at, updated_at) VALUES (
  'tpl_listening_intermediate', 'listening-intermediate', 'Listening — Intermediate', 'Thirty listening tasks covering summarise spoken text, dictation, fill in the blanks and highlight incorrect words.', 'module', 'listening',
  'intermediate', 1, 'AUD', 30,
  35, 65, 'Complete every task in order. Timing is per task where the PTE exam is timed per task; the overall limit applies to the whole test.', 0, 1, 1, NULL, '2026-01-05T00:00:00.000Z', '2026-01-05T00:00:00.000Z');
DELETE FROM test_template_rules WHERE template_id = 'tpl_listening_intermediate';
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_listening-intermediate_summarize_spoken_text', 'tpl_listening_intermediate', 'summarize_spoken_text', 2, NULL, 1, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_listening-intermediate_listening_mcq_multiple', 'tpl_listening_intermediate', 'listening_mcq_multiple', 4, NULL, 2, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_listening-intermediate_listening_fill_blanks', 'tpl_listening_intermediate', 'listening_fill_blanks', 4, NULL, 3, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_listening-intermediate_highlight_correct_summary', 'tpl_listening_intermediate', 'highlight_correct_summary', 4, NULL, 4, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_listening-intermediate_listening_mcq_single', 'tpl_listening_intermediate', 'listening_mcq_single', 4, NULL, 5, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_listening-intermediate_select_missing_word', 'tpl_listening_intermediate', 'select_missing_word', 4, NULL, 6, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_listening-intermediate_highlight_incorrect_words', 'tpl_listening_intermediate', 'highlight_incorrect_words', 4, NULL, 7, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_listening-intermediate_write_from_dictation', 'tpl_listening_intermediate', 'write_from_dictation', 4, NULL, 8, '2026-01-05T00:00:00.000Z');

INSERT OR REPLACE INTO test_templates (id, slug, name, description, test_type, module_key, difficulty,
  price, currency, question_count, time_limit_minutes, target_score, instructions, is_active, purchasable,
  version, created_by, created_at, updated_at) VALUES (
  'tpl_listening_hard', 'listening-hard', 'Listening — Hard', 'Thirty listening tasks covering summarise spoken text, dictation, fill in the blanks and highlight incorrect words.', 'module', 'listening',
  'hard', 1, 'AUD', 30,
  35, 79, 'Complete every task in order. Timing is per task where the PTE exam is timed per task; the overall limit applies to the whole test.', 0, 1, 1, NULL, '2026-01-05T00:00:00.000Z', '2026-01-05T00:00:00.000Z');
DELETE FROM test_template_rules WHERE template_id = 'tpl_listening_hard';
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_listening-hard_summarize_spoken_text', 'tpl_listening_hard', 'summarize_spoken_text', 2, NULL, 1, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_listening-hard_listening_mcq_multiple', 'tpl_listening_hard', 'listening_mcq_multiple', 4, NULL, 2, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_listening-hard_listening_fill_blanks', 'tpl_listening_hard', 'listening_fill_blanks', 4, NULL, 3, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_listening-hard_highlight_correct_summary', 'tpl_listening_hard', 'highlight_correct_summary', 4, NULL, 4, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_listening-hard_listening_mcq_single', 'tpl_listening_hard', 'listening_mcq_single', 4, NULL, 5, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_listening-hard_select_missing_word', 'tpl_listening_hard', 'select_missing_word', 4, NULL, 6, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_listening-hard_highlight_incorrect_words', 'tpl_listening_hard', 'highlight_incorrect_words', 4, NULL, 7, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_listening-hard_write_from_dictation', 'tpl_listening_hard', 'write_from_dictation', 4, NULL, 8, '2026-01-05T00:00:00.000Z');

INSERT OR REPLACE INTO test_templates (id, slug, name, description, test_type, module_key, difficulty,
  price, currency, question_count, time_limit_minutes, target_score, instructions, is_active, purchasable,
  version, created_by, created_at, updated_at) VALUES (
  'tpl_speaking_starter_set', 'speaking-starter-set', 'Speaking Starter Set', 'A short speaking practice set with one question from every task type in the module.', 'practice_set', 'speaking',
  'mixed', 1, 'AUD', 7,
  15, 65, 'A short warm-up set: one question from each task type in this module. Complete every task in order.', 1, 1, 1, NULL, '2026-01-05T00:00:00.000Z', '2026-01-05T00:00:00.000Z');
DELETE FROM test_template_rules WHERE template_id = 'tpl_speaking_starter_set';
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_speaking-starter-set_read_aloud', 'tpl_speaking_starter_set', 'read_aloud', 1, NULL, 1, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_speaking-starter-set_repeat_sentence', 'tpl_speaking_starter_set', 'repeat_sentence', 1, NULL, 2, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_speaking-starter-set_describe_image', 'tpl_speaking_starter_set', 'describe_image', 1, NULL, 3, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_speaking-starter-set_retell_lecture', 'tpl_speaking_starter_set', 'retell_lecture', 1, NULL, 4, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_speaking-starter-set_answer_short_question', 'tpl_speaking_starter_set', 'answer_short_question', 1, NULL, 5, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_speaking-starter-set_respond_to_situation', 'tpl_speaking_starter_set', 'respond_to_situation', 1, NULL, 6, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_speaking-starter-set_summarize_group_discussion', 'tpl_speaking_starter_set', 'summarize_group_discussion', 1, NULL, 7, '2026-01-05T00:00:00.000Z');

INSERT OR REPLACE INTO test_templates (id, slug, name, description, test_type, module_key, difficulty,
  price, currency, question_count, time_limit_minutes, target_score, instructions, is_active, purchasable,
  version, created_by, created_at, updated_at) VALUES (
  'tpl_reading_starter_set', 'reading-starter-set', 'Reading Starter Set', 'A short reading practice set with one question from every task type in the module.', 'practice_set', 'reading',
  'mixed', 1, 'AUD', 5,
  16, 65, 'A short warm-up set: one question from each task type in this module. Complete every task in order.', 1, 1, 1, NULL, '2026-01-05T00:00:00.000Z', '2026-01-05T00:00:00.000Z');
DELETE FROM test_template_rules WHERE template_id = 'tpl_reading_starter_set';
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_reading-starter-set_reading_writing_fill_blanks', 'tpl_reading_starter_set', 'reading_writing_fill_blanks', 1, NULL, 1, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_reading-starter-set_reading_mcq_multiple', 'tpl_reading_starter_set', 'reading_mcq_multiple', 1, NULL, 2, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_reading-starter-set_reorder_paragraphs', 'tpl_reading_starter_set', 'reorder_paragraphs', 1, NULL, 3, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_reading-starter-set_reading_fill_blanks', 'tpl_reading_starter_set', 'reading_fill_blanks', 1, NULL, 4, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_reading-starter-set_reading_mcq_single', 'tpl_reading_starter_set', 'reading_mcq_single', 1, NULL, 5, '2026-01-05T00:00:00.000Z');

INSERT OR REPLACE INTO test_templates (id, slug, name, description, test_type, module_key, difficulty,
  price, currency, question_count, time_limit_minutes, target_score, instructions, is_active, purchasable,
  version, created_by, created_at, updated_at) VALUES (
  'tpl_writing_starter_set', 'writing-starter-set', 'Writing Starter Set', 'A short writing practice set with one question from every task type in the module.', 'practice_set', 'writing',
  'mixed', 1, 'AUD', 2,
  20, 65, 'A short warm-up set: one question from each task type in this module. Complete every task in order.', 1, 1, 1, NULL, '2026-01-05T00:00:00.000Z', '2026-01-05T00:00:00.000Z');
DELETE FROM test_template_rules WHERE template_id = 'tpl_writing_starter_set';
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_writing-starter-set_summarize_written_text', 'tpl_writing_starter_set', 'summarize_written_text', 1, NULL, 1, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_writing-starter-set_write_essay', 'tpl_writing_starter_set', 'write_essay', 1, NULL, 2, '2026-01-05T00:00:00.000Z');

INSERT OR REPLACE INTO test_templates (id, slug, name, description, test_type, module_key, difficulty,
  price, currency, question_count, time_limit_minutes, target_score, instructions, is_active, purchasable,
  version, created_by, created_at, updated_at) VALUES (
  'tpl_listening_starter_set', 'listening-starter-set', 'Listening Starter Set', 'A short listening practice set with one question from every task type in the module.', 'practice_set', 'listening',
  'mixed', 1, 'AUD', 8,
  18, 65, 'A short warm-up set: one question from each task type in this module. Complete every task in order.', 1, 1, 1, NULL, '2026-01-05T00:00:00.000Z', '2026-01-05T00:00:00.000Z');
DELETE FROM test_template_rules WHERE template_id = 'tpl_listening_starter_set';
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_listening-starter-set_summarize_spoken_text', 'tpl_listening_starter_set', 'summarize_spoken_text', 1, NULL, 1, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_listening-starter-set_listening_mcq_multiple', 'tpl_listening_starter_set', 'listening_mcq_multiple', 1, NULL, 2, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_listening-starter-set_listening_fill_blanks', 'tpl_listening_starter_set', 'listening_fill_blanks', 1, NULL, 3, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_listening-starter-set_highlight_correct_summary', 'tpl_listening_starter_set', 'highlight_correct_summary', 1, NULL, 4, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_listening-starter-set_listening_mcq_single', 'tpl_listening_starter_set', 'listening_mcq_single', 1, NULL, 5, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_listening-starter-set_select_missing_word', 'tpl_listening_starter_set', 'select_missing_word', 1, NULL, 6, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_listening-starter-set_highlight_incorrect_words', 'tpl_listening_starter_set', 'highlight_incorrect_words', 1, NULL, 7, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_listening-starter-set_write_from_dictation', 'tpl_listening_starter_set', 'write_from_dictation', 1, NULL, 8, '2026-01-05T00:00:00.000Z');

INSERT OR REPLACE INTO test_templates (id, slug, name, description, test_type, module_key, difficulty,
  price, currency, question_count, time_limit_minutes, target_score, instructions, is_active, purchasable,
  version, created_by, created_at, updated_at) VALUES (
  'tpl_full_mock_mixed', 'full-mock-mixed', 'Complete Mock Test — All Modules', 'A full four-module mock test with mixed difficulty: Speaking, Reading, Writing and Listening in exam order.', 'mock', NULL,
  'mixed', 5, 'AUD', 34,
  137, 65, 'This mock test runs in exam order: Speaking, Writing, Reading and then Listening. Allow the full time in one sitting.', 0, 1, 1, NULL, '2026-01-05T00:00:00.000Z', '2026-01-05T00:00:00.000Z');
DELETE FROM test_template_rules WHERE template_id = 'tpl_full_mock_mixed';
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_full-mock-mixed_read_aloud', 'tpl_full_mock_mixed', 'read_aloud', 3, NULL, 1, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_full-mock-mixed_repeat_sentence', 'tpl_full_mock_mixed', 'repeat_sentence', 4, NULL, 2, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_full-mock-mixed_describe_image', 'tpl_full_mock_mixed', 'describe_image', 2, NULL, 3, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_full-mock-mixed_retell_lecture', 'tpl_full_mock_mixed', 'retell_lecture', 1, NULL, 4, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_full-mock-mixed_answer_short_question', 'tpl_full_mock_mixed', 'answer_short_question', 2, NULL, 5, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_full-mock-mixed_summarize_written_text', 'tpl_full_mock_mixed', 'summarize_written_text', 2, NULL, 6, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_full-mock-mixed_write_essay', 'tpl_full_mock_mixed', 'write_essay', 1, NULL, 7, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_full-mock-mixed_reading_writing_fill_blanks', 'tpl_full_mock_mixed', 'reading_writing_fill_blanks', 3, NULL, 8, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_full-mock-mixed_reading_mcq_multiple', 'tpl_full_mock_mixed', 'reading_mcq_multiple', 2, NULL, 9, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_full-mock-mixed_reorder_paragraphs', 'tpl_full_mock_mixed', 'reorder_paragraphs', 2, NULL, 10, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_full-mock-mixed_reading_fill_blanks', 'tpl_full_mock_mixed', 'reading_fill_blanks', 2, NULL, 11, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_full-mock-mixed_reading_mcq_single', 'tpl_full_mock_mixed', 'reading_mcq_single', 1, NULL, 12, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_full-mock-mixed_summarize_spoken_text', 'tpl_full_mock_mixed', 'summarize_spoken_text', 1, NULL, 13, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_full-mock-mixed_listening_mcq_multiple', 'tpl_full_mock_mixed', 'listening_mcq_multiple', 2, NULL, 14, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_full-mock-mixed_listening_fill_blanks', 'tpl_full_mock_mixed', 'listening_fill_blanks', 2, NULL, 15, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_full-mock-mixed_highlight_correct_summary', 'tpl_full_mock_mixed', 'highlight_correct_summary', 1, NULL, 16, '2026-01-05T00:00:00.000Z');
INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at) VALUES ('ttr_full-mock-mixed_write_from_dictation', 'tpl_full_mock_mixed', 'write_from_dictation', 3, NULL, 17, '2026-01-05T00:00:00.000Z');
