/**
 * Emits migrations/0006_test_template_seed.sql from the shared
 * `defaultTemplates` definition so D1 and the local memory store seed the same
 * catalogue. Run with: bun run scripts/gen-template-seed.ts
 */
import { writeFileSync } from "node:fs";

import {
  defaultTemplates,
  distributionToRules,
  sumRules,
  templatePrice,
} from "../src/config/tests";
import { pricingConfig } from "../src/config/site";

const CREATED = "2026-01-05T00:00:00.000Z";
const q = (value: string | number | null) =>
  value === null ? "NULL" : typeof value === "number" ? String(value) : `'${value.replace(/'/g, "''")}'`;

const lines: string[] = [
  "-- 0006_test_template_seed.sql — default module + mock test templates",
  "-- GENERATED by scripts/gen-template-seed.ts — do not edit by hand.",
  "-- Apply with: wrangler d1 migrations apply pte_portal",
  "",
  "PRAGMA foreign_keys = ON;",
  "",
];

for (const def of defaultTemplates) {
  const id = `tpl_${def.slug.replace(/-/g, "_")}`;
  const rules = distributionToRules(def.distribution);
  lines.push(
    `INSERT OR REPLACE INTO test_templates (id, slug, name, description, test_type, module_key, difficulty,`,
    `  price, currency, question_count, time_limit_minutes, target_score, instructions, is_active, purchasable,`,
    `  version, created_by, created_at, updated_at) VALUES (`,
    `  ${q(id)}, ${q(def.slug)}, ${q(def.name)}, ${q(def.description)}, ${q(def.testType)}, ${q(def.module)},`,
    `  ${q(def.difficulty)}, ${q(templatePrice(def.testType))}, ${q(pricingConfig.currency)}, ${q(sumRules(rules))},`,
    `  ${q(def.timeLimitMinutes)}, ${q(def.targetScore)}, ${q(def.instructions)}, ${def.isActive === false ? 0 : 1}, 1, 1, NULL, ${q(CREATED)}, ${q(CREATED)});`,
    `DELETE FROM test_template_rules WHERE template_id = ${q(id)};`,
  );
  for (const rule of rules) {
    lines.push(
      `INSERT INTO test_template_rules (id, template_id, type_key, question_count, difficulty, position, created_at)` +
        ` VALUES (${q(`ttr_${def.slug}_${rule.typeKey}`)}, ${q(id)}, ${q(rule.typeKey)}, ${q(rule.questionCount)}, NULL, ${q(rule.position)}, ${q(CREATED)});`,
    );
  }
  lines.push("");
}

writeFileSync("migrations/0006_test_template_seed.sql", lines.join("\n"));
console.log(`Wrote ${defaultTemplates.length} templates to migrations/0006_test_template_seed.sql`);
