/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as StudentRouteImport } from './routes/student'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as TestModulesRouteImport } from './routes/test-modules'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAiEvaluationsRouteImport } from './routes/admin.ai-evaluations'
import { Route as AdminAuditLogsRouteImport } from './routes/admin.audit-logs'
import { Route as AdminContentImportsRouteImport } from './routes/admin.content-imports'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminPlatformSettingsRouteImport } from './routes/admin.platform-settings'
import { Route as AdminQuestionsRouteImport } from './routes/admin.questions'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminTestAttemptsRouteImport } from './routes/admin.test-attempts'
import { Route as AdminTestTemplatesRouteImport } from './routes/admin.test-templates'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as StudentAccountSettingsRouteImport } from './routes/student.account-settings'
import { Route as StudentAiRecommendationsRouteImport } from './routes/student.ai-recommendations'
import { Route as StudentBrowseTestsRouteImport } from './routes/student.browse-tests'
import { Route as StudentMyTestsRouteImport } from './routes/student.my-tests'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentProgressRouteImport } from './routes/student.progress'
import { Route as StudentPurchasesRouteImport } from './routes/student.purchases'
import { Route as StudentTestHistoryRouteImport } from './routes/student.test-history'
import { Route as ApiPublicAuthActionRouteImport } from './routes/api/public/auth/$action'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const TestModulesRoute = TestModulesRouteImport.update({
  id: '/test-modules',
  path: '/test-modules',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiEvaluationsRoute = AdminAiEvaluationsRouteImport.update({
  id: '/ai-evaluations',
  path: '/ai-evaluations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentImportsRoute = AdminContentImportsRouteImport.update({
  id: '/content-imports',
  path: '/content-imports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlatformSettingsRoute = AdminPlatformSettingsRouteImport.update({
  id: '/platform-settings',
  path: '/platform-settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuestionsRoute = AdminQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestAttemptsRoute = AdminTestAttemptsRouteImport.update({
  id: '/test-attempts',
  path: '/test-attempts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestTemplatesRoute = AdminTestTemplatesRouteImport.update({
  id: '/test-templates',
  path: '/test-templates',
  getParentRoute: () => AdminRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAccountSettingsRoute = StudentAccountSettingsRouteImport.update({
  id: '/account-settings',
  path: '/account-settings',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAiRecommendationsRoute =
  StudentAiRecommendationsRouteImport.update({
    id: '/ai-recommendations',
    path: '/ai-recommendations',
    getParentRoute: () => StudentRoute,
  } as any)
const StudentBrowseTestsRoute = StudentBrowseTestsRouteImport.update({
  id: '/browse-tests',
  path: '/browse-tests',
  getParentRoute: () => StudentRoute,
} as any)
const StudentMyTestsRoute = StudentMyTestsRouteImport.update({
  id: '/my-tests',
  path: '/my-tests',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProgressRoute = StudentProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => StudentRoute,
} as any)
const StudentPurchasesRoute = StudentPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => StudentRoute,
} as any)
const StudentTestHistoryRoute = StudentTestHistoryRouteImport.update({
  id: '/test-history',
  path: '/test-history',
  getParentRoute: () => StudentRoute,
} as any)
const ApiPublicAuthActionRoute = ApiPublicAuthActionRouteImport.update({
  id: '/api/public/auth/$action',
  path: '/api/public/auth/$action',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/student': typeof StudentRouteWithChildren
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/test-modules': typeof TestModulesRoute
  '/admin/ai-evaluations': typeof AdminAiEvaluationsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/content-imports': typeof AdminContentImportsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/platform-settings': typeof AdminPlatformSettingsRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/test-attempts': typeof AdminTestAttemptsRoute
  '/admin/test-templates': typeof AdminTestTemplatesRoute
  '/student/account-settings': typeof StudentAccountSettingsRoute
  '/student/ai-recommendations': typeof StudentAiRecommendationsRoute
  '/student/browse-tests': typeof StudentBrowseTestsRoute
  '/student/my-tests': typeof StudentMyTestsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/progress': typeof StudentProgressRoute
  '/student/purchases': typeof StudentPurchasesRoute
  '/student/test-history': typeof StudentTestHistoryRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/api/public/auth/$action': typeof ApiPublicAuthActionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/test-modules': typeof TestModulesRoute
  '/admin/ai-evaluations': typeof AdminAiEvaluationsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/content-imports': typeof AdminContentImportsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/platform-settings': typeof AdminPlatformSettingsRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/test-attempts': typeof AdminTestAttemptsRoute
  '/admin/test-templates': typeof AdminTestTemplatesRoute
  '/student/account-settings': typeof StudentAccountSettingsRoute
  '/student/ai-recommendations': typeof StudentAiRecommendationsRoute
  '/student/browse-tests': typeof StudentBrowseTestsRoute
  '/student/my-tests': typeof StudentMyTestsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/progress': typeof StudentProgressRoute
  '/student/purchases': typeof StudentPurchasesRoute
  '/student/test-history': typeof StudentTestHistoryRoute
  '/admin': typeof AdminIndexRoute
  '/student': typeof StudentIndexRoute
  '/api/public/auth/$action': typeof ApiPublicAuthActionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/student': typeof StudentRouteWithChildren
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/test-modules': typeof TestModulesRoute
  '/admin/ai-evaluations': typeof AdminAiEvaluationsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/content-imports': typeof AdminContentImportsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/platform-settings': typeof AdminPlatformSettingsRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/test-attempts': typeof AdminTestAttemptsRoute
  '/admin/test-templates': typeof AdminTestTemplatesRoute
  '/student/account-settings': typeof StudentAccountSettingsRoute
  '/student/ai-recommendations': typeof StudentAiRecommendationsRoute
  '/student/browse-tests': typeof StudentBrowseTestsRoute
  '/student/my-tests': typeof StudentMyTestsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/progress': typeof StudentProgressRoute
  '/student/purchases': typeof StudentPurchasesRoute
  '/student/test-history': typeof StudentTestHistoryRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/api/public/auth/$action': typeof ApiPublicAuthActionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/disclaimer'
    | '/forgot-password'
    | '/how-it-works'
    | '/login'
    | '/pricing'
    | '/privacy-policy'
    | '/register'
    | '/reset-password'
    | '/student'
    | '/terms-and-conditions'
    | '/test-modules'
    | '/admin/ai-evaluations'
    | '/admin/audit-logs'
    | '/admin/content-imports'
    | '/admin/coupons'
    | '/admin/payments'
    | '/admin/platform-settings'
    | '/admin/questions'
    | '/admin/reports'
    | '/admin/students'
    | '/admin/test-attempts'
    | '/admin/test-templates'
    | '/student/account-settings'
    | '/student/ai-recommendations'
    | '/student/browse-tests'
    | '/student/my-tests'
    | '/student/profile'
    | '/student/progress'
    | '/student/purchases'
    | '/student/test-history'
    | '/admin/'
    | '/student/'
    | '/api/public/auth/$action'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/disclaimer'
    | '/forgot-password'
    | '/how-it-works'
    | '/login'
    | '/pricing'
    | '/privacy-policy'
    | '/register'
    | '/reset-password'
    | '/terms-and-conditions'
    | '/test-modules'
    | '/admin/ai-evaluations'
    | '/admin/audit-logs'
    | '/admin/content-imports'
    | '/admin/coupons'
    | '/admin/payments'
    | '/admin/platform-settings'
    | '/admin/questions'
    | '/admin/reports'
    | '/admin/students'
    | '/admin/test-attempts'
    | '/admin/test-templates'
    | '/student/account-settings'
    | '/student/ai-recommendations'
    | '/student/browse-tests'
    | '/student/my-tests'
    | '/student/profile'
    | '/student/progress'
    | '/student/purchases'
    | '/student/test-history'
    | '/admin'
    | '/student'
    | '/api/public/auth/$action'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/disclaimer'
    | '/forgot-password'
    | '/how-it-works'
    | '/login'
    | '/pricing'
    | '/privacy-policy'
    | '/register'
    | '/reset-password'
    | '/student'
    | '/terms-and-conditions'
    | '/test-modules'
    | '/admin/ai-evaluations'
    | '/admin/audit-logs'
    | '/admin/content-imports'
    | '/admin/coupons'
    | '/admin/payments'
    | '/admin/platform-settings'
    | '/admin/questions'
    | '/admin/reports'
    | '/admin/students'
    | '/admin/test-attempts'
    | '/admin/test-templates'
    | '/student/account-settings'
    | '/student/ai-recommendations'
    | '/student/browse-tests'
    | '/student/my-tests'
    | '/student/profile'
    | '/student/progress'
    | '/student/purchases'
    | '/student/test-history'
    | '/admin/'
    | '/student/'
    | '/api/public/auth/$action'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  DisclaimerRoute: typeof DisclaimerRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  StudentRoute: typeof StudentRouteWithChildren
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  TestModulesRoute: typeof TestModulesRoute
  ApiPublicAuthActionRoute: typeof ApiPublicAuthActionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-modules': {
      id: '/test-modules'
      path: '/test-modules'
      fullPath: '/test-modules'
      preLoaderRoute: typeof TestModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai-evaluations': {
      id: '/admin/ai-evaluations'
      path: '/ai-evaluations'
      fullPath: '/admin/ai-evaluations'
      preLoaderRoute: typeof AdminAiEvaluationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content-imports': {
      id: '/admin/content-imports'
      path: '/content-imports'
      fullPath: '/admin/content-imports'
      preLoaderRoute: typeof AdminContentImportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/platform-settings': {
      id: '/admin/platform-settings'
      path: '/platform-settings'
      fullPath: '/admin/platform-settings'
      preLoaderRoute: typeof AdminPlatformSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/questions': {
      id: '/admin/questions'
      path: '/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AdminQuestionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/test-attempts': {
      id: '/admin/test-attempts'
      path: '/test-attempts'
      fullPath: '/admin/test-attempts'
      preLoaderRoute: typeof AdminTestAttemptsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/test-templates': {
      id: '/admin/test-templates'
      path: '/test-templates'
      fullPath: '/admin/test-templates'
      preLoaderRoute: typeof AdminTestTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/account-settings': {
      id: '/student/account-settings'
      path: '/account-settings'
      fullPath: '/student/account-settings'
      preLoaderRoute: typeof StudentAccountSettingsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/ai-recommendations': {
      id: '/student/ai-recommendations'
      path: '/ai-recommendations'
      fullPath: '/student/ai-recommendations'
      preLoaderRoute: typeof StudentAiRecommendationsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/browse-tests': {
      id: '/student/browse-tests'
      path: '/browse-tests'
      fullPath: '/student/browse-tests'
      preLoaderRoute: typeof StudentBrowseTestsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/my-tests': {
      id: '/student/my-tests'
      path: '/my-tests'
      fullPath: '/student/my-tests'
      preLoaderRoute: typeof StudentMyTestsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/progress': {
      id: '/student/progress'
      path: '/progress'
      fullPath: '/student/progress'
      preLoaderRoute: typeof StudentProgressRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/purchases': {
      id: '/student/purchases'
      path: '/purchases'
      fullPath: '/student/purchases'
      preLoaderRoute: typeof StudentPurchasesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/test-history': {
      id: '/student/test-history'
      path: '/test-history'
      fullPath: '/student/test-history'
      preLoaderRoute: typeof StudentTestHistoryRouteImport
      parentRoute: typeof StudentRoute
    }
    '/api/public/auth/$action': {
      id: '/api/public/auth/$action'
      path: '/api/public/auth/$action'
      fullPath: '/api/public/auth/$action'
      preLoaderRoute: typeof ApiPublicAuthActionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAiEvaluationsRoute: typeof AdminAiEvaluationsRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminContentImportsRoute: typeof AdminContentImportsRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPlatformSettingsRoute: typeof AdminPlatformSettingsRoute
  AdminQuestionsRoute: typeof AdminQuestionsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminTestAttemptsRoute: typeof AdminTestAttemptsRoute
  AdminTestTemplatesRoute: typeof AdminTestTemplatesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAiEvaluationsRoute: AdminAiEvaluationsRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminContentImportsRoute: AdminContentImportsRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPlatformSettingsRoute: AdminPlatformSettingsRoute,
  AdminQuestionsRoute: AdminQuestionsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminTestAttemptsRoute: AdminTestAttemptsRoute,
  AdminTestTemplatesRoute: AdminTestTemplatesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StudentRouteChildren {
  StudentAccountSettingsRoute: typeof StudentAccountSettingsRoute
  StudentAiRecommendationsRoute: typeof StudentAiRecommendationsRoute
  StudentBrowseTestsRoute: typeof StudentBrowseTestsRoute
  StudentMyTestsRoute: typeof StudentMyTestsRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentProgressRoute: typeof StudentProgressRoute
  StudentPurchasesRoute: typeof StudentPurchasesRoute
  StudentTestHistoryRoute: typeof StudentTestHistoryRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentAccountSettingsRoute: StudentAccountSettingsRoute,
  StudentAiRecommendationsRoute: StudentAiRecommendationsRoute,
  StudentBrowseTestsRoute: StudentBrowseTestsRoute,
  StudentMyTestsRoute: StudentMyTestsRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentProgressRoute: StudentProgressRoute,
  StudentPurchasesRoute: StudentPurchasesRoute,
  StudentTestHistoryRoute: StudentTestHistoryRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  DisclaimerRoute: DisclaimerRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  StudentRoute: StudentRouteWithChildren,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  TestModulesRoute: TestModulesRoute,
  ApiPublicAuthActionRoute: ApiPublicAuthActionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
